name: javascript/prettier

permissions:
  contents: read

on:
  push:
    branches: [ main, feature/swig ]
    paths:
      - 'javascript/**/*.js'
      - 'javascript/**/*.json'
      - '.github/workflows/javascript/prettier.yml'

  pull_request:
    branches: [ main, feature/swig ]

jobs:
  check-source-changes:
    runs-on: ubuntu-latest
    outputs:
      run_job: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check for changes in JavaScript source code
        id: changed-files
        uses: tj-actions/changed-files@c3a1bb2c992d77180ae65be6ae6c166cf40f857c # v46.0.1
        with:
          files: |
            javascript/**/*.js
            javascript/**/*.json
            .github/workflows/javascript/prettier.yml

  prettier:
    runs-on: ubuntu-latest
    needs: check-source-changes
    if: needs.check-source-changes.outputs.run_job == 'true'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Set up Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: javascript/package-lock.json

      - name: Install Prettier
        run: npm install -g prettier@3.2.4

      - name: Run Prettier
        run: prettier --check "javascript/**/*.{js,json}"
